const heading = {
  fontFamily: 'heading',
  fontWeight: 'heading',
  lineHeight: 'heading',
}
const commonButtonStyles = {
  py: 2,
  px: 3,
  fontWeight: 'bold',
  textTransform: 'uppercase',
  cursor: `pointer`,
  fontSize: `100%`,
  lineHeight: `inherit`,
}

const buttons = {
  simple: {
    ...commonButtonStyles,
    backgroundColor: `primary`,
    border: `none`,
    color: `white`,
    fontWeight: `bold`,
    borderRadius: `default`,
    '&:hover': {
      backgroundColor: `primaryHover`,
    },
  },
  pill: {
    ...commonButtonStyles,
    backgroundColor: `primary`,
    border: `none`,
    color: `white`,
    fontWeight: `bold`,
    borderRadius: `full`,
    '&:hover': {
      backgroundColor: `primaryHover`,
    },
  },
  outline: {
    ...commonButtonStyles,
    backgroundColor: `transparent`,
    borderWidth: `1px`,
    borderStyle: `solid`,
    borderColor: `primaryDark`,
    color: `primaryDark`,
    fontWeight: `semibold`,
    borderRadius: `default`,
    '&:hover': {
      backgroundColor: `primaryLight`,
      color: `white`,
      borderColor: `transparent`,
    },
  },
  bordered: {
    ...commonButtonStyles,
    backgroundColor: `primary`,
    borderWidth: `1px`,
    borderStyle: `solid`,
    borderColor: `primaryHover`,
    color: `white`,
    fontWeight: `bold`,
    borderRadius: `default`,
    '&:hover': {
      backgroundColor: `primaryHover`,
    },
  },
  disabled: {
    ...commonButtonStyles,
    backgroundColor: `primary`,
    border: `none`,
    opacity: 0.5,
    cursor: `not-allowed`,
    color: `white`,
    fontWeight: `bold`,
    borderRadius: `default`,
  },
  source: {
    ...commonButtonStyles,
    backgroundColor: 'white',
    color: 'text',
    border: '3px solid #e7e7e7',

    ':hover': {
      backgroundColor: '#e7e7e7',
    },
  },
}

const theme = {
  useCustomProperties: true,
  useBorderBox: true,
  colors: {
    transparent: 'transparent',
    black: '#000',
    white: '#fff',
    gray: [
      null,
      '#FFFFFF',
      '#f7fafc',
      '#edf2f7',
      '#e2e8f0',
      '#cbd5e0',
      '#a0aec0',
      '#718096',
      '#4a5568',
      '#2d3748',
      '#1a202c',
    ],
    red: [
      null,
      '#fff5f5',
      '#fed7d7',
      '#feb2b2',
      '#fc8181',
      '#f56565',
      '#e53e3e',
      '#c53030',
      '#9b2c2c',
      '#742a2a',
    ],
    orange: [
      null,
      '#fffaf0',
      '#feebc8',
      '#fbd38d',
      '#f6ad55',
      '#ed8936',
      '#dd6b20',
      '#c05621',
      '#9c4221',
      '#7b341e',
    ],
    yellow: [
      null,
      '#fffff0',
      '#fefcbf',
      '#faf089',
      '#f6e05e',
      '#ecc94b',
      '#d69e2e',
      '#b7791f',
      '#975a16',
      '#744210',
    ],
    green: [
      null,
      '#f0fff4',
      '#c6f6d5',
      '#9ae6b4',
      '#68d391',
      '#48bb78',
      '#38a169',
      '#2f855a',
      '#276749',
      '#22543d',
    ],
    teal: [
      null,
      '#e6fffa',
      '#b2f5ea',
      '#81e6d9',
      '#4fd1c5',
      '#38b2ac',
      '#319795',
      '#2c7a7b',
      '#285e61',
      '#234e52',
    ],
    blue: [
      null,
      '#ebf8ff',
      '#bee3f8',
      '#90cdf4',
      '#63b3ed',
      '#4299e1',
      '#3182ce',
      '#2b6cb0',
      '#2c5282',
      '#2a4365',
    ],
    indigo: [
      null,
      '#ebf4ff',
      '#c3dafe',
      '#a3bffa',
      '#7f9cf5',
      '#667eea',
      '#5a67d8',
      '#4c51bf',
      '#434190',
      '#3c366b',
    ],
    purple: [
      null,
      '#faf5ff',
      '#e9d8fd',
      '#d6bcfa',
      '#b794f4',
      '#9f7aea',
      '#805ad5',
      '#6b46c1',
      '#553c9a',
      '#44337a',
    ],
    accent: 'rgba(243,147, 55,1)',
    accent2: 'rgba(255,193,135,1)',
    accent3: 'rgba(255,172, 93,1)',
    accent4: 'rgba(215,113, 16,1)',
    accent5: 'rgba(169, 84,  3,1)',
    grayDark: '#2d3748',
    hotgradient:
      'background-image: linear-gradient(to right, rgb(250, 112, 154) 0%, rgb(254, 225, 64) 100%)',
    hotpink: 'rgb(250, 112, 154)',
    coolyellow: '',
    hero1: '#292a2d',
    hero2: '#3b3d42',
    primary: '#292a2d',
    secondary: '#3b3d42',
    primaryHover: '#2c5282',
    muted: '#e2e8f0',
    success: '#9ae6b4',
    info: '#63b3ed',
    warning: '#faf089',
    danger: '#feb2b2',
    light: '#f7fafc',
    dark: '#2d3748',
    textMuted: '#718096',
    eerieblack: '#252323',
    text: 'rgba(80, 81, 79, 1)',
    background: '#FFFFFF',
    orangesoda: '#F06449',
    platinum: '#EDE6E3',
    gainsboro: '#DADAD9',
    blackolive: '#36382E',
    skyblue: '#5BC3EB',
    primaryDark: '#bf0603',
    primaryLight: 'rgba(254, 147, 140, 1)',
    blueDark: 'rgba(25, 130, 196, 1)',
    purpleDark: 'rgba(83, 58, 113, 1)',
    highlight: '#F9FBFB',
    contact: '#003459',
    footer: '#F5F1ED',
    slategray: '#70798C',
    bone: '#DAD2BC',
    grullo: '#A99985',
    carolinablue: '#00A5E0',
    lightblue: '#39A9DB',
    bluegreen: '#40BCD8',
    bluegreenlight: '#60cde5',
    saffron: '#F39237',
    persianred: '#D63230',
    coolred: '#f55555',
  },
  layout: {
    container: {
      maxWidth: '1200px',
      mx: ['1em', '2em'],
      px: 'em',
    },
    about: {
      bg: '#FFFFFF',
    },
    projects: {
      bg: '#F8F9FA',
    },
    miniapps: {
      bg: '#F8F9FA',
    },
    contact: {
      bg: 'secondary',
    },
    footer: {
      px: 4,
      py: 3,
      bg: 'blackolive',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
    },
  },
  fonts: {
    sans:
      '"Inter UI",system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji"',
    serif: 'Georgia,Cambria,"Times New Roman",Times,serif',
    mono:
      '"SF Mono","Roboto Mono",Monaco,Consolas,"Liberation Mono","Courier New",monospace',
    body:
      '"Inter",system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji"',
    heading: 'inherit',
    monospace:
      'Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace',
  },
  fontWeights: {
    body: 400,
    bold: 600,
    heading: 700,
    display: 900,
  },
  zIndices: ['auto', '0', '10', '20', '30', '40', '50'],
  fontSizes: [
    '0.75rem',
    '0.875rem',
    '1rem',
    '1.25rem',
    '1.5rem',
    '1.75rem',
    '2rem',
    '2.25rem',
    '2.5rem',
    '3rem',
    '3.5rem',
    '4.5rem',
    '5.5rem',
    '6.5rem',
  ],
  letterSpacings: {
    tighter: '-0.05em',
    tight: '-0.025em',
    normal: '0',
    wide: '0.025em',
    wider: '0.05em',
    heading: '-0.05em',
    widest: '0.1em',
  },
  lineHeights: {
    none: '1',
    tight: '1.25',
    snug: '1.375',
    normal: '1.5',
    relaxed: '1.625',
    loose: '2',
    body: '1.625',
    heading: '1.25',
  },
  sizes: {
    '0': '0',
    '1': '0.25rem',
    '2': '0.5rem',
    '3': '0.75rem',
    '4': '1rem',
    '5': '1.25rem',
    '6': '1.5rem',
    '8': '2rem',
    '10': '2.5rem',
    '12': '3rem',
    '16': '4rem',
    '20': '5rem',
    '24': '6rem',
    '32': '8rem',
    '40': '10rem',
    '48': '12rem',
    '56': '14rem',
    '64': '16rem',
    px: '1px',
    xs: '20rem',
    sm: '24rem',
    md: '28rem',
    lg: '32rem',
    xl: '36rem',
    container: 1300,
    header: 800,
    full: '100%',
    screenHeight: '100vh',
    screenWidth: '100vw',
  },
  shadows: {
    xs: '0 0 0 1px rgba(0, 0, 0, 0.05)',
    sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
    default: '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
    md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
    lg:
      '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
    xl:
      '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
    '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
    inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
    outline: '0 0 0 3px rgba(66, 153, 225, 0.5)',
    none: 'none',
  },
  space: [0, 4, 8, 16, 32, 64, 128, 256, 512],
  breakpoints: ['40em', '52em', '64em', '80em'],
  imageStyles: {
    Hero: {
      WebkitBoxShadow:
        '0 0 1px 11px rgba(80, 81, 79, .15), 0 0 1px 22px rgba(80, 81, 79, .1)',
      boxShadow:
        '0 0 1px 11px rgba(80, 81, 79, .15), 0 0 1px 22px rgba(80, 81, 79, .1)',
      borderRadius: '50%',
      transform: `rotate(-35deg)`,
      position: 'absolute',
      top: 'unset',
      bottom: 0,
      right: 0,
      width: '100%',
      objectFit: 'contain',
      objectPosition: 'center',
      userSelect: 'none',
      transition: 'transform .5s, filter 1.5s ease-in-out',
    },
  },
  textStyles: {
    heading,
    display: {
      variant: 'textStyles.heading',
      color: 'saffron',
      fontSize: [7, 8],
      fontWeight: 'display',
      letterSpacing: 'tight',
    },
    subDisplay: {
      variant: 'textStyles.heading',
      color: '#f6f6f6',
      fontSize: [2, 3],
      fontWeight: 'body',
      letterSpacing: 'tight',
    },
    projectTitle: {
      variant: 'textStyles.heading',
      fontSize: [6, 7],
      color: 'black',
      p: 5,
      letterSpacing: 'tight',
    },
  },
  radii: {
    none: '0',
    sm: '0.125rem',
    default: '0.25rem',
    md: '0.375rem',
    lg: '0.5rem',
    full: '9999px',
  },
  borders: {
    thick: '2px solid var(--theme-ui-colors-text, black)',
    thin: '1px solid var(--theme-ui-colors-text, black)',
  },
  styles: {
    root: {
      fontFamily: 'body',
      lineHeight: 'body',
      fontWeight: 'body',
    },
    p: {
      color: 'text',
      fontSize: [0, 1],
    },
    a: {
      color: 'primary',
      textDecoration: 'none',
    },
    h1: {
      fontFamily: 'heading',
      lineHeight: 'heading',
      color: 'saffron',
      fontSize: [7, 8],
      fontWeight: 'display',
      letterSpacing: 'tight',
    },
    h2: {
      fontFamily: 'heading',
      lineHeight: 'heading',
    },
    h3: {
      fontFamily: 'heading',
      fontWeight: 'heading',
      lineHeight: 'heading',
      fontSize: [4, 5],
    },
    h4: {
      fontFamily: 'heading',
      fontWeight: 'heading',
      lineHeight: 'heading',
      fontSize: [3, 4],
    },
    h5: {
      fontFamily: 'heading',
      lineHeight: 'heading',
      color: '#f6f6f6',
      fontSize: [2, 3],
      fontWeight: 'body',
      letterSpacing: 'tight',
    },
    h6: {
      fontFamily: 'heading',
      fontWeight: 'heading',
      lineHeight: 'heading',
      fontSize: [1, 2],
    },
    img: {
      maxWidth: '100%',
      height: 'auto',
    },
  },
  images: {
    avatar: {
      width: 140,
      height: 140,
      objectFit: 'cover',
      objectPosition: '50% 50%',
      WebkitBoxShadow:
        '0 0 1px 11px rgba(80, 81, 79, .15), 0 0 1px 22px rgba(80, 81, 79, .1)',
      boxShadow:
        '0 0 1px 11px rgba(80, 81, 79, .15), 0 0 1px 22px rgba(80, 81, 79, .1)',
      borderRadius: '9999px',
      transform: `rotate(-35deg)`,
    },
    icon: {
      width: 5,
      height: 5,
      borderRadius: 99999,
    },
  },
  alerts: {
    primary: {
      color: 'background',
      bg: 'primary',
    },
    muted: {
      color: 'text',
      bg: 'muted',
    },
  },
  badges: {
    primary: {
      color: 'secondary',
      bg: 'primary',
      fontSize: ['8px', '10px'],
    },
    outline: {
      p: 1,
      px: 2,
      fontSize: ['8px', '10px'],
      color: 'black',
      border: '2px dashed',
      borderColor: 'gray.5',
      bg: 'gray.3',
    },
  },
  cards: {
    primary: {
      padding: 2,
      borderRadius: 4,
      boxShadow: '0 0 8px rgba(0, 0, 0, 0.125)',
    },
    compact: {
      padding: 1,
      borderRadius: 2,
      border: '1px solid',
      borderColor: 'muted',
      transition: 'all 0.3s ease',
      '&:hover': {
        border: '1px solid',
        borderColor: 'gray.6',
      },
    },
  },
  buttons: {
    ...buttons,
    demo: {
      cursor: 'pointer',
      color: 'white',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      p: 2,
      outline: 'none',
      bg: `blue.5`,
      width: '100%',
      borderRadius: 'sm',
      transition: 'all 0.3s ease',
      '&:hover': {
        transition: '0.2s ease-in',
        bg: 'blue.4',
      },
    },
    source: {
      cursor: 'pointer',
      color: 'white',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      p: 2,
      outline: 'none',
      bg: `indigo.3`,
      width: '100%',
      borderRadius: 'sm',
      transition: 'all 0.3s ease',
      '&:hover': {
        transition: '0.2s ease-in',
        bg: 'persianred',
      },
    },
  },
  forms: {
    label: {
      fontSize: 1,
      color: 'muted',
    },
    input: {
      borderWidth: '3px',
      borderStyle: 'solid',
      borderImageSlice: '1',
      borderImageSource: (themes) =>
        `linear-gradient(to left, ${themes.colors.info}, ${themes.colors.warning})`,
      color: 'white',
      outline: 'none',
      bg: 'secondary',
      mb: 3,
    },
    textarea: {
      borderWidth: '3px',
      borderStyle: 'solid',
      borderImageSlice: '1',
      borderImageSource: (themes) =>
        `linear-gradient(to left, ${themes.colors.info}, ${themes.colors.warning})`,
      color: 'white',
      outline: 'none',
      bg: 'secondary',
      mb: 3,
    },
  },
  links: {
    color: 'primary',
    nav: {
      fontSize: [1, 2],
      textDecoration: 'none',
      p: 2,
      '&:hover': {
        transition: '0.2s ease-in',
        color: '#f6f6f6',
      },
    },
  },
}

module.exports = theme
